// 🔥 Auto-generated Live Components Registration
// This file is automatically generated during build time - DO NOT EDIT MANUALLY
// Generated at: 2026-02-24T00:00:00.000Z

import { LiveSchemaDesigner } from "@app/server/live/LiveSchemaDesigner"
import { LiveUpload } from "@app/server/live/LiveUpload"
import { componentRegistry } from "@core/server/live/ComponentRegistry"

// Register all components statically for production bundle
function registerAllComponents() {
  try {
    // Auto-generated component registrations
    componentRegistry.registerComponentClass('LiveSchemaDesigner', LiveSchemaDesigner)
    componentRegistry.registerComponentClass('LiveUpload', LiveUpload)

    console.log('📝 Live components registered successfully! (2 components)')
  } catch (error) {
    console.warn('⚠️ Error registering components:', error)
  }
}

// Auto-register components
registerAllComponents()

// Export all components to ensure they're included in the bundle
export {
  LiveSchemaDesigner,
  LiveUpload
}
