// 🔥 Auto-generated Live Components Registration
// This file is automatically generated during build time - DO NOT EDIT MANUALLY
// Generated at: 2026-02-21T20:03:53.569Z

import { LiveAdminPanel } from "@app/server/live/LiveAdminPanel"
import { LiveChat } from "@app/server/live/LiveChat"
import { LiveCounter } from "@app/server/live/LiveCounter"
import { LiveForm } from "@app/server/live/LiveForm"
import { LiveLocalCounter } from "@app/server/live/LiveLocalCounter"
import { LiveProtectedChat } from "@app/server/live/LiveProtectedChat"
import { LiveRoomChat } from "@app/server/live/LiveRoomChat"
import { LiveUpload } from "@app/server/live/LiveUpload"
import { componentRegistry } from "@core/server/live/ComponentRegistry"

// Register all components statically for production bundle
function registerAllComponents() {
  try {
    // Auto-generated component registrations
    componentRegistry.registerComponentClass('LiveAdminPanel', LiveAdminPanel)
    componentRegistry.registerComponentClass('LiveChat', LiveChat)
    componentRegistry.registerComponentClass('LiveCounter', LiveCounter)
    componentRegistry.registerComponentClass('LiveForm', LiveForm)
    componentRegistry.registerComponentClass('LiveLocalCounter', LiveLocalCounter)
    componentRegistry.registerComponentClass('LiveProtectedChat', LiveProtectedChat)
    componentRegistry.registerComponentClass('LiveRoomChat', LiveRoomChat)
    componentRegistry.registerComponentClass('LiveUpload', LiveUpload)
    
    console.log('📝 Live components registered successfully! (8 components)')
  } catch (error) {
    console.warn('⚠️ Error registering components:', error)
  }
}

// Auto-register components
registerAllComponents()

// Export all components to ensure they're included in the bundle
export { 
  LiveAdminPanel,
  LiveChat,
  LiveCounter,
  LiveForm,
  LiveLocalCounter,
  LiveProtectedChat,
  LiveRoomChat,
  LiveUpload
}
